name: poker_agent
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.2
  - numpy=1.26
  - pandas=2.2
  - pyarrow
  - tqdm
  - matplotlib
  - seaborn
  - pytest
  - pip:
    - open_spiel
    - treys
    - phevaluator
    - phh
    - wandb
